const PROJECT_COLLECTION = 'projects'
const ABOUT_COLLECTION = 'about'
const ABOUT_DOC = 'helendkim'
const LANDING_COLLECTION = 'landing'

export { PROJECT_COLLECTION, ABOUT_COLLECTION, LANDING_COLLECTION, ABOUT_DOC }
